### ISSUE TITLE
Potential Release Date?

### ISSUE THREAD

**Issue by TacoDeluxeYT** [Goobwabber/MultiplayerCore#5]
Do you have a potential idea as to when this will be made available. If you are unsure it is ok I've just been really wanting to play the multiplayer on the recent update.

**Comment by whymoo** [comment]
Never ask for an eta for anything free like this, it's just rude. This kind of project is a lot of work not only for the usual reasons of modding being hard for a closed source game like beat saber but because multiplayer also requires a server to be coded and tested. I suggest you downgrade your game, and if you're too lazy to do that why should a dev do the infinitely harder task of updating the mod? Also if you want development to go faster I suggest you support Goobwabber or BeatTogether on patreon. Why do you even have a github account if your asking something like this?

**Comment by TacoDeluxeYT** [comment]
I am not being rude there are way more people that are worse in situations like this I have seen and if I was rude I would have constantly asked about it. The creator has the decision to reply to my post and answer but I was never expecting an answer because I don't need one. I was never impatient about the progress and if I was I could just downgrade which I have awhile back. Thank you for replying to my original message on behalf of the creator.
Taco Deluxe :)

**Comment by Goobwabber** [comment]
soon:tm:
